Structural improvements

diff --git a/punts/gh-repo b/punts/gh-repo
--- a/punts/gh-repo
+++ b/punts/gh-repo
@@ -26,24 +26,24 @@ ${obj}__fill_url() {
     echo "$(printf "$url_pattern" "${${obj}_user}" "${${obj}_repo}")"
 }
 
-${obj}_get_download_urls() {
-    if [[ -z ${${obj}_download_urls} ]]; then
+${obj}_get_release_download_urls() {
+    if [[ -z ${${obj}_release_download_urls} ]]; then
         local url="$(
             ${obj}__fill_url "https://api.github.com/repos/%s/%s/releases/latest"
         )"
 
-        ${obj}_download_urls="$(${obj}_get_api_data browser_download_url "$url")"
+        ${obj}_release_download_urls="$(${obj}_get_api_data browser_download_url "$url")"
     fi
 
     echo "${${obj}_download_urls}"
 }
 
-${obj}_get_asset_names() {
-    [[ -z "${${obj}_asset_names}" ]] && ${obj}_asset_names="$(
-        basename "$(${obj}_get_download_urls)"
+${obj}_get_release_asset_names() {
+    [[ -z "${${obj}_release_asset_names}" ]] && ${obj}_release_asset_names="$(
+        basename "$(${obj}_get_release_download_urls)"
     )"
 
-    echo "${${obj}_asset_names}"
+    echo "${${obj}_release_asset_names}"
 }
 
 ${obj}_get_remote_version() {
@@ -59,19 +59,17 @@ ${obj}_get_remote_version() {
 }
 
 ${obj}_get_local_version() {
-    msg -e "Not implemented: This method would get the local version of the program: Implemented in \`cli-program\` object"
-    return 1
+    msg -w "Not implemented: Returns the local version of the program"
 }
 
 ${obj}_is_latest() {
     local remote_version="$(${obj}_get_remote_version)"
     local local_version="$(${obj}_get_local_version)"
 
-    [ "$local_version" == "$remote_version" ] && return 0 \
-                                              || return 1
+    [ "$local_version" == "$remote_version" ] || return 1
 }
 
-${obj}_download_asset() {
+${obj}_download_release_asset() {
     local asset_name="$1"
     local output="$2"
 
@@ -99,31 +97,32 @@ ${obj}_release_menu() {
 
     echo "Detected operating system: $os_name \nDetected architecture: $arch_name"
 
-    local asset_names="$(${obj}_get_asset_names)"
+    local asset_names="$(${obj}_get_release_asset_names)"
 
-    local release_names_with_arch_and_os="$(echo "$asset_names" | grep -Ei "$os_name.*$arch_name|$arch_name.*$os_name")"
-    local release_names_with_arch_or_os="$(echo "$asset_names" | grep -Ei "$os_name|$arch_name")"
+    local asset_names_with_arch_and_os="$(
+        echo "$asset_names" | grep -Ei "$os_name.*$arch_name|$arch_name.*$os_name"
+    )"
+    local asset_names_with_arch_or_os="$(
+        echo "$asset_names" | grep -Ei "$os_name|$arch_name"
+    )"
 
-    local release_names=""
-    if [[ ! "$release_names_with_arch_and_os" == "" ]]; then
-        release_names="$release_names_with_arch_and_os"
-    elif [[ ! "$release_names_with_arch_or_os" == "" ]]; then
-        release_names="$release_names_with_arch_or_os"
-    else
-        release_names="$asset_names"
+    if [[ ! "$asset_names_with_arch_and_os" == "" ]]; then
+        asset_names="$asset_names_with_arch_and_os"
+    elif [[ ! "$asset_names_with_arch_or_os" == "" ]]; then
+        asset_names="$asset_names_with_arch_or_os"
     fi
 
-    local selected_release=""
-    PS3="Select a release to download: "
-    select release in $release_names; do
-        if [[ -n "$release" ]]; then
-            selected_release="$release"
+    local selected_asset
+    PS3="Select the asset to download: "
+    select asset in $asset_names; do
+        if [[ -n "$asset" ]]; then
+            selected_asset="$asset"
             break
         else
-            echo "Invalid selection, please choose a valid release."
+            echo "Invalid selection, please choose a valid asset."
         fi
     done
 
-    echo "$selected_release"
+    echo "$selected_asset"
 }
 
